const regularAPI = async () => {
  const data = await fetch('https://academy-award-oscar.herokuapp.com/movies');

  const result = await data.json()
  return result;
}

const graphqlAPI = async () => {
  const data = await fetch('https://academy-award-oscar.herokuapp.com/graphql', {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      query: `
      {
        actors{
            name 
        	}
        }
      `
    })
  });

  const result = await data.json()
  return result.data;
}

const postActor = async (name) => {
  const data = await fetch('https://academy-award-oscar.herokuapp.com/graphql', {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      query: `
      mutation {
        	createActor (input: {data: {name: "${name}"}}) {
        		actor {
        			name
        		}
        	}
        }
      `
    })
  });

  const result = await data.json()
  console.log("Recorded in Actors: ", result.data);
  return result.data;
}

const allActors = [
  "Javier Bardem",
  "Russell Crowe",
  "Tom Hanks",
  "Ed Harris",
  "Geoffrey Rush",
  "Jeff Bridges",
  "Willem Dafoe",
  "Benicio Del Toro",
  "Albert Finney",
  "Joaquin Phoenix",
  "Joan Allen",
  "Juliette Binoche",
  "Ellen Burstyn",
  "Laura Linney",
  "Julia Roberts",
  "Judi Dench",
  "Marcia Gay Harden",
  "Kate Hudson",
  "Frances McDormand",
  "Julie Walters",
  "Dino De Laurentiis",
  "Irwin W. Young",
  "Russell Crowe",
  "Sean Penn",
  "Will Smith",
  "Denzel Washington",
  "Tom Wilkinson",
  "Jim Broadbent",
  "Ethan Hawke",
  "Ben Kingsley",
  "Ian McKellen",
  "Jon Voight",
  "Halle Berry",
  "Judi Dench",
  "Nicole Kidman",
  "Sissy Spacek",
  "RenÃ©e Zellweger",
  "Jennifer Connelly",
  "Helen Mirren",
  "Maggie Smith",
  "Marisa Tomei",
  "Kate Winslet",
  "Arthur Hiller",
  "Edmund M. Di Giulio",
  "Adrien Brody",
  "Nicolas Cage",
  "Michael Caine",
  "Daniel Day-Lewis",
  "Jack Nicholson",
  "Chris Cooper",
  "Ed Harris",
  "Paul Newman",
  "John C. Reilly",
  "Christopher Walken",
  "Salma Hayek",
  "Nicole Kidman",
  "Diane Lane",
  "Julianne Moore",
  "RenÃ©e Zellweger",
  "Kathy Bates",
  "Julianne Moore",
  "Queen Latifah",
  "Meryl Streep",
  "Catherine Zeta-Jones",
  "Johnny Depp",
  "Ben Kingsley",
  "Jude Law",
  "Bill Murray",
  "Sean Penn",
  "Alec Baldwin",
  "Benicio Del Toro",
  "Djimon Hounsou",
  "Tim Robbins",
  "Ken Watanabe",
  "Keisha Castle-Hughes",
  "Diane Keaton",
  "Samantha Morton",
  "Charlize Theron",
  "Naomi Watts",
  "Shohreh Aghdashloo",
  "Patricia Clarkson",
  "Marcia Gay Harden",
  "Holly Hunter",
  "RenÃ©e Zellweger",
  "Peter D. Parks",
  "Don Cheadle",
  "Johnny Depp",
  "Leonardo DiCaprio",
  "Clint Eastwood",
  "Jamie Foxx",
  "Alan Alda",
  "Thomas Haden Church",
  "Jamie Foxx",
  "Morgan Freeman",
  "Clive Owen",
  "Annette Bening",
  "Catalina Sandino Moreno",
  "Imelda Staunton",
  "Hilary Swank",
  "Kate Winslet",
  "Cate Blanchett",
  "Laura Linney",
  "Virginia Madsen",
  "Sophie Okonedo",
  "Natalie Portman",
  "Roger Mayer",
  "Takuo Miyagishima",
  "Philip Seymour Hoffman",
  "Terrence Howard",
  "Heath Ledger",
  "Joaquin Phoenix",
  "David Strathairn",
  "George Clooney",
  "Matt Dillon",
  "Paul Giamatti",
  "Jake Gyllenhaal",
  "William Hurt",
  "Judi Dench",
  "Felicity Huffman",
  "Keira Knightley",
  "Charlize Theron",
  "Reese Witherspoon",
  "Amy Adams",
  "Catherine Keener",
  "Frances McDormand",
  "Rachel Weisz",
  "Michelle Williams",
  "Gary Demos",
  "Leonardo DiCaprio",
  "Ryan Gosling",
  "Peter O'Toole",
  "Will Smith",
  "Forest Whitaker",
  "Alan Arkin",
  "Jackie Earle Haley",
  "Djimon Hounsou",
  "Eddie Murphy",
  "Mark Wahlberg",
  "PenÃ©lope Cruz",
  "Judi Dench",
  "Helen Mirren",
  "Meryl Streep",
  "Kate Winslet",
  "Adriana Barraza",
  "Cate Blanchett",
  "Abigail Breslin",
  "Jennifer Hudson",
  "Rinko Kikuchi",
  "Sherry Lansing",
  "Ray Feeney",
  "George Clooney",
  "Daniel Day-Lewis",
  "Johnny Depp",
  "Tommy Lee Jones",
  "Viggo Mortensen",
  "Casey Affleck",
  "Javier Bardem",
  "Philip Seymour Hoffman",
  "Hal Holbrook",
  "Tom Wilkinson",
  "Cate Blanchett",
  "Julie Christie",
  "Marion Cotillard",
  "Laura Linney",
  "Ellen Page",
  "Cate Blanchett",
  "Ruby Dee",
  "Saoirse Ronan",
  "Amy Ryan",
  "Tilda Swinton",
  "David A. Grafton",
  "Richard Jenkins",
  "Frank Langella",
  "Sean Penn",
  "Brad Pitt",
  "Mickey Rourke",
  "Josh Brolin",
  "Robert Downey Jr.",
  "Philip Seymour Hoffman",
  "Heath Ledger",
  "Michael Shannon",
  "Anne Hathaway",
  "Angelina Jolie",
  "Melissa Leo",
  "Meryl Streep",
  "Kate Winslet",
  "Amy Adams",
  "PenÃ©lope Cruz",
  "Viola Davis",
  "Taraji P. Henson",
  "Marisa Tomei",
  "Jerry Lewis",
  "Ed Catmull",
  "Jeff Bridges",
  "George Clooney",
  "Colin Firth",
  "Morgan Freeman",
  "Jeremy Renner",
  "Matt Damon",
  "Woody Harrelson",
  "Christopher Plummer",
  "Stanley Tucci",
  "Christoph Waltz",
  "Sandra Bullock",
  "Helen Mirren",
  "Carey Mulligan",
  "Gabourey Sidibe",
  "Meryl Streep",
  "PenÃ©lope Cruz",
  "Vera Farmiga",
  "Maggie Gyllenhaal",
  "Anna Kendrick",
  "Mo'Nique",
  "John Calley",
  "Javier Bardem",
  "Jeff Bridges",
  "Jesse Eisenberg",
  "Colin Firth",
  "James Franco",
  "Christian Bale",
  "John Hawkes",
  "Jeremy Renner",
  "Mark Ruffalo",
  "Geoffrey Rush",
  "Annette Bening",
  "Nicole Kidman",
  "Jennifer Lawrence",
  "Natalie Portman",
  "Michelle Williams",
  "Amy Adams",
  "Helena Bonham Carter",
  "Melissa Leo",
  "Hailee Steinfeld",
  "Jacki Weaver",
  "Francis Ford Coppola",
  "DemiÃ¡n Bichir",
  "George Clooney",
  "Jean Dujardin",
  "Gary Oldman",
  "Brad Pitt",
  "Kenneth Branagh",
  "Jonah Hill",
  "Nick Nolte",
  "Christopher Plummer",
  "Max von Sydow",
  "Glenn Close",
  "Viola Davis",
  "Rooney Mara",
  "Meryl Streep",
  "Michelle Williams",
  "BÃ©rÃ©nice Bejo",
  "Jessica Chastain",
  "Melissa McCarthy",
  "Janet McTeer",
  "Octavia Spencer",
  "Oprah Winfrey",
  "Douglas Trumbull",
  "Bradley Cooper",
  "Daniel Day-Lewis",
  "Hugh Jackman",
  "Joaquin Phoenix",
  "Denzel Washington",
  "Alan Arkin",
  "Robert De Niro",
  "Philip Seymour Hoffman",
  "Tommy Lee Jones",
  "Christoph Waltz",
  "Jessica Chastain",
  "Jennifer Lawrence",
  "Emmanuelle Riva",
  "QuvenzhanÃ© Wallis",
  "Naomi Watts",
  "Amy Adams",
  "Sally Field",
  "Anne Hathaway",
  "Helen Hunt",
  "Jacki Weaver",
  "Jeffrey Katzenberg",
  "Christian Bale",
  "Bruce Dern",
  "Leonardo DiCaprio",
  "Chiwetel Ejiofor",
  "Matthew McConaughey",
  "Barkhad Abdi",
  "Bradley Cooper",
  "Michael Fassbender",
  "Jonah Hill",
  "Jared Leto",
  "Amy Adams",
  "Cate Blanchett",
  "Sandra Bullock",
  "Judi Dench",
  "Meryl Streep",
  "Sally Hawkins",
  "Jennifer Lawrence",
  "Lupita Nyong'o",
  "Julia Roberts",
  "June Squibb",
  "Angelina Jolie",
  "Peter W. Anderson",
  "Steve Carell",
  "Bradley Cooper",
  "Benedict Cumberbatch",
  "Michael Keaton",
  "Eddie Redmayne",
  "Robert Duvall",
  "Ethan Hawke",
  "Edward Norton",
  "Mark Ruffalo",
  "J.K. Simmons",
  "Marion Cotillard",
  "Felicity Jones",
  "Julianne Moore",
  "Rosamund Pike",
  "Reese Witherspoon",
  "Patricia Arquette",
  "Laura Dern",
  "Keira Knightley",
  "Emma Stone",
  "Meryl Streep",
  "Harry Belafonte",
  "David Winchester Gray",
  "Bryan Cranston",
  "Matt Damon",
  "Leonardo DiCaprio",
  "Michael Fassbender",
  "Eddie Redmayne",
  "Christian Bale",
  "Tom Hardy",
  "Mark Ruffalo",
  "Mark Rylance",
  "Sylvester Stallone",
  "Cate Blanchett",
  "Brie Larson",
  "Jennifer Lawrence",
  "Charlotte Rampling",
  "Saoirse Ronan",
  "Jennifer Jason Leigh",
  "Rooney Mara",
  "Rachel McAdams",
  "Alicia Vikander",
  "Kate Winslet",
  "Debbie Reynolds",
  "Casey Affleck",
  "Andrew Garfield",
  "Ryan Gosling",
  "Viggo Mortensen",
  "Denzel Washington",
  "Mahershala Ali",
  "Jeff Bridges",
  "Lucas Hedges",
  "Dev Patel",
  "Michael Shannon",
  "Isabelle Huppert",
  "Ruth Negga",
  "Natalie Portman",
  "Emma Stone",
  "Meryl Streep",
  "Viola Davis",
  "Naomie Harris",
  "Nicole Kidman",
  "Octavia Spencer",
  "Michelle Williams",
  "TimothÃ©e Chalamet",
  "Daniel Day-Lewis",
  "Daniel Kaluuya",
  "Gary Oldman",
  "Denzel Washington",
  "Willem Dafoe",
  "Woody Harrelson",
  "Richard Jenkins",
  "Christopher Plummer",
  "Sam Rockwell",
  "Sally Hawkins",
  "Frances McDormand",
  "Margot Robbie",
  "Saoirse Ronan",
  "Meryl Streep",
  "Mary J. Blige",
  "Allison Janney",
  "Lesley Manville",
  "Laurie Metcalf",
  "Octavia Spencer",
  "Jonathan Erland",
  ]
 
export default function Home(props) {
  //console.log('regular API: ',props.regularAPI)
  console.log('GraphQL API: ',props.graphqlAPI)
  
  return (
    <div>
        <h1>Test</h1>
    </div>
  )
}

export const getServerSideProps = async () => {
  const myRegularAPI = await regularAPI();
  const myGraphqlAPI = await graphqlAPI();

  //Post all actors in database
  //allActors.forEach(actor => postActor(actor) );
  
  return { props: {regularAPI: myRegularAPI, graphqlAPI: myGraphqlAPI} };
}
